# Generated by Django 5.0.4 on 2024-04-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
