# Generated by Django 5.0.4 on 2024-04-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_business_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='location_building_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='location_sub_county',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='location_ward',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
