# Generated by Django 5.0.4 on 2024-05-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_business_location_building_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(choices=[('FinTech', 'FinTech'), ('Learning Institute', 'Learning Institute'), ('Transportation', 'Transportation'), ('Service', 'Service'), ('Banking', 'Banking'), ('other', 'other')], max_length=50),
        ),
    ]
