# Generated by Django 5.0.4 on 2024-05-05 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_business_age_alter_business_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
