# Generated by Django 5.0.4 on 2024-05-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_business_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='owner',
            new_name='customer',
        ),
    ]
